### PR TITLE
Update code to check if directory already mounted

### PR DESCRIPTION
**Pull request by pietrobr**
Check if directory already mounted before adding, otherwise error.

### CODE REVIEW

**Comment by pietrobr** [comment]
No problem

**Comment by DawnmarieDesJardins** [comment]
Thank you!
I've marked this as an enhancement and your change will be reviewed with the next schedule update.

**Comment by mrfalafel** [comment]
Thanks @pietrobr, the mount check made into September update.

**Comment by DawnmarieDesJardins** [comment]
Closing as address in September 2019 update

**Pull request closed without merging**
